config/routes.rb
Writings::Application.routes.draw do
  root 'pages#home'

  devise_for :admins
  resources :books do
    resources :entries, shallow: true
  end

  get 'entries' => 'entries#index'

  resources :categories

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :about

  has_many :entries, dependent: :destroy
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :entry_categories, dependent: :destroy
  has_many :entries, through: :entry_categories

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  before_save :replace_new_lines

  validates_presence_of :contents
  validates_presence_of :title

  has_many :entry_categories, dependent: :destroy
  has_many :categories, through: :entry_categories

  belongs_to :book
  validates_presence_of :book

  def date
    Writings::Date.new( year, month, day ).to_s
  end

  protected

  def replace_new_lines
    contents.gsub!( /\r\n/, "<br>" )
    contents.gsub!( "</p><br>", "</p>" )
  end

end

app/models/entry_category.rb
class EntryCategory < ActiveRecord::Base

  belongs_to :entry
  belongs_to :category

  validates_presence_of :category

end

app/models/writings/date.rb
module Writings

  class Date

    def initialize( year, month, day )
      @year  = year
      @month = month
      @day   = day
    end

    def to_s
      state = 0
      state += 1 if @year
      state += 2 if @month
      state += 4 if @day

      case state
      when 0; 'Date Unknown'
      when 1; "#{@year}"
      when 2; month_str
      when 3; month_str + ', ' + @year
      when 4; 'A day numbered: ' + @day
      when 5; "#{@year}"
      when 6; "#{month_str} #{@day}"
      when 7; "#{month_str} #{@day}, #{@year}"
      end

    end

    protected

    def month_str
      @@months = [ 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec' ]
      @@months[ @month - 1 ]
    end


  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [ :show, :edit, :update, :destroy ]
  before_action :find_entries, only: [ :show ]
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy ]

  def new
    @book = Book.new
  end

  def create
    @book  = Book.new( book_params )
    if @book.save
      redirect_to book_path( @book ), notice: 'Book Created'
    else
      render :new
    end
  end

  def show
  end

  def index
    @books = Book.all
  end

  def edit
  end

  def update
    if @book.update( book_params )
      redirect_to book_path( @book ), notice: 'Book Updated'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: 'Book Destroyed'
  end

  protected
  def book_params
    params.require(:book).permit( :title, :about )
  end

  def find_book
    @book = Book.find( params[:id] )
  end

  def find_entries
    @entries = @book.entries
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy ]

  def new
    @category = Category.new
  end

  def create
    @category  = Category.new( category_params )
    if @category.save
      redirect_to category_path( @category ), notice: 'Category Created'
    else
      render :new
    end
  end

  def show
    @entries = Entry.joins( :entry_categories ).where( "entry_categories.category_id =  #{@category.id}" ).select( "title, year, month, day, entries.id" )
  end

  def index
    @categories = Category.all
  end

  def edit
  end

  def update
    if @category.update( category_params )
      redirect_to category_path( @category ), notice: 'Category Updated'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to entries_path, notice: 'Category Destroyed'
  end

  protected
  def category_params
    params.require(:category).permit( :name )
  end

  def find_category
    @category = Category.find( params[:id] )
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :find_entry, only: [ :show, :edit, :update, :destroy ]
  before_action :find_book, only: [ :new, :create, :index ]
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy ]

  def new
    @entry = Entry.new
    @categories = Category.all
  end

  def create
    @entry  = @book.entries.build( entry_params )
    if @entry.save
      redirect_to entry_path( @entry ), notice: 'Entry Created'
    else
      render :new
    end
  end

  def show
    @categories = Category.joins( :entry_categories ).where( "entry_categories.entry_id = #{@entry.id} " ).select( "name, categories.id " )
    @category_class = @categories.first.name.downcase.gsub( / /, '_' ) if @categories.any?
  end

  def index
    @entries = @book ? @book.entries : Entry.all
  end

  def edit
    @categories = Category.all
  end

  def update
    if @entry.update( entry_params )
      redirect_to entry_path( @entry ), notice: 'Entry Updated'
    else
      render :edit
    end
  end

  def destroy
    @book = @entry.book
    @entry.destroy
    redirect_to book_path( @book ) , notice: 'Entry Destroyed'
  end

  protected
  def entry_params
    params.require(:entry).permit( :title, :contents, :year, :month, :day, category_ids: [] )
  end

  def find_entry
    @entry = Entry.find( params[:id] )
  end

  def find_book
    @book = Book.find( params[ :book_id ] )
  rescue
    @book = nil
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def create_link( title, url, options = {} )
    link_to( title, url, options )
  end

  def create_links( links = {} )
    links.map { |k,v| content_tag :li, create_link( k, v[:url], v[:options ] ) }.join
  end

  def link_list( links = {} )
    content_tag :ul, ( create_links( links ).html_safe )
  end

  def edit_destroy_links( resource )
    return '' unless current_admin
    resource_name = pluralize(2, resource.class.to_s.downcase ).split()[1]
    edit_url      = "/#{resource_name}/#{resource.id}/edit"
    destroy_url   = "/#{resource_name}/#{resource.id}"

    link_list(
      'Edit'    => { url: edit_url },
      'Destroy' => { url: destroy_url, options: { method: :delete } }
    )

  end

end

app/helpers/books_helper.rb
module BooksHelper

  def admin_show_options
    return unless current_admin
    link_list(
      'Add Entry' => { url: new_book_entry_path( @book ) },
      'Edit'      => { url: edit_book_path( @book ) },
      'Destroy'   => { url: book_path( @book ), options: { method: :delete } }
    )
  end

end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/books/_form.html.erb
<% if book.errors.any? %>
  <div class='error_message'>
    <ul>
      <% @book.errors.full_messages.each do | message | %>
        <p><%= message %></p>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for book do | form | %>
  <%= content_tag :p, title %>
  <%= form.text_field :title, { placeholder: 'Title', required: true, class: 'center' } %>
  <%= form.text_area :about, placeholder: 'Tell me about the book', required: true %>
  <%= form.submit %>
<% end %>

app/views/books/edit.html.erb
<%= render partial: 'form', locals: { title: 'Edit a Book', book: @book } %>

app/views/books/index.html.erb
<% @books.each do | book | %>
  <section class='book_overview'>
    <aside><h2><%= link_to book.title, book_path( book ) %><h2></aside>
    <article><%= sanitize( book.about ) %><%= content_tag(:p, edit_destroy_links( book )) if current_admin %></article>
  </section>
<% end %>
<%= link_to( 'Create Book', new_book_path ) if current_admin %>

app/views/books/new.html.erb
<%= render partial: 'form', locals: { title: 'Create a book', book: @book } %>

app/views/books/show.html.erb
<%= content_tag :h1, @book.title %>
<%= content_tag :h2, sanitize( @book.about ) %>

<ul>
  <% @entries.each do | entry | %>
    <li><%= link_to entry.title, entry_path( entry ) %></li>
  <% end %>
</ul>

<%= admin_show_options %>

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div class='error_message'>
    <ul>
      <% @category.errors.full_messages.each do | message | %>
        <p><%= message %></p>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @category do | form | %>
  <%= content_tag :p, title %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/categories/edit.html.erb
<%= render partial: 'form', locals: { title: 'Edit a Category', category: @category } %>

app/views/categories/index.html.erb
<table>
  <th>Name</th>
  <%= content_tag( :th, 'Options' ) if current_admin %>
  <% @categories.each do | category | %>
    <tr>
      <td><%= link_to category.name, category_path( category ) %></td>
      <%= content_tag( :td, edit_destroy_links( category ) ) if current_admin %>
    </tr>
  <% end %>
</table>
<%= link_to( 'Create Category', new_category_path ) if current_admin %>

app/views/categories/new.html.erb
<%= render partial: 'form', locals: { title: 'Create a Category', category: @category } %>

app/views/categories/show.html.erb
<%= content_tag :h1, @category.name %>

<ul>
  <% @entries.each do | entry | %>
    <li><%= link_to("#{entry.title}: #{entry.date}", entry_path( entry )) %></li>
  <% end %>
</ul>

<%= edit_destroy_links( @category ) %>

app/views/entries/_form.html.erb
<% if @entry.errors.any? %>
  <div class='error_message'>
    <ul>
      <% @entry.errors.full_messages.each do | message | %>
        <p><%= message %></p>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [ @book, @entry ] do | form | %>
  <%= content_tag :p, title %>
  <%= form.text_field :title, placeholder: 'Title', required: true %>
  <%= form.number_field :year, placeholder: 'Year' %>
  <%= form.number_field :month, placeholder: 'Month' %>
  <%= form.number_field :day, placeholder: 'Day'   %>
  <%= form.text_area :contents %>
  <fieldset>
    <legend>Categories</legend>
    <%= form.collection_check_boxes(:category_ids, @categories, :id, :name ) %>
  </fieldset>
  <%= form.submit %>
<% end %>

app/views/entries/edit.html.erb
<%= render partial: 'form', locals: { title: 'Edit an Entry', entry: @entry } %>

app/views/entries/index.html.erb
<table>
  <th>Title</th>
  <th>Date</th>
  <th>Book</th>
  <%= content_tag( :th, 'Options' ) if current_admin %>
  <% @entries.each do | entry | %>
    <tr>
      <td><%= link_to entry.title, entry_path( entry ) %></td>
      <td><%= entry.date  %></td>
      <td><%= link_to entry.book.title, book_path( entry.book ) %></td>
      <%= content_tag( :td, edit_destroy_links( entry ) ) if current_admin %>
    </tr>
  <% end %>
</table>
<%= link_to( 'Create Entry', new_book_entry_path( @book ) ) if @book && current_admin %>

app/views/entries/new.html.erb
<%= render partial: 'form', locals: { title: "Create an entry for #{@book.title}", entry: @entry } %>

app/views/entries/show.html.erb
<div class='entry'>
  <section class='title'>
    <%= content_tag :aside, @entry.title %>
    <%= content_tag :article, @entry.date %>
  </section>
  <%= content_tag :div, sanitize( @entry.contents ), class: @category_class %>
</div>

<ul>
  <li><%= link_to "Add another entry", new_book_entry_path( @entry.book ) %>
  <li><%= link_to "Back to #{@entry.book.title}", book_path( @entry.book ) %></li>
  <% @categories.each do | category | %>
    <li><%= link_to "Other #{ pluralize( 2, category.name ).split()[1..-1].join(' ') }", category_path( category ) %></li>
  <% end %>
  <li><%= link_to "All Entries", entries_path %></li>
</ul>


<%= edit_destroy_links( @entry ) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Writings</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id='nav'>
  <h1><%= link_to 'Writings', root_path %></h1>
  <%= link_list(
        'Books'      => { url: books_path },
        'Entries'    => { url: entries_path },
        'Categories' => { url: categories_path }) %>
</div>

<div id='content'>
  <%= content_tag :p, notice, class: 'notice' %>
  <%= content_tag :p, alert, class: 'alert' %>
  <%= yield %>
</div>

<div id='footer'>
  <% if current_admin %>
    <%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %>
  <% else %>
    <%= link_to 'admin?', new_admin_session_path %>
  <% end %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<h1 class='center'>Things that I wrote</h1>
<div id='introduction'>
  <p>Between the years of 2000 and 2006 I wrote many things</p>
  <p>I never read them, and have been carring them in a box since then.</p>
  <p>This page is an attempt to get through the things that I wrote.</p>
</div>